version: "3"
services:
  api:
    image: smidge:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7001:443"
      - "7000:80"
  #  depends_on:
  #    - db

  #db:
  #  image: postgres:latest
  #  restart: always
  #  environment:
  #    POSTGRES_USER: your_username
  #    POSTGRES_PASSWORD: your_password
  #    POSTGRES_DB: your_database
  #  ports:
  #    - "5432:5432"
